export const students = [
    {
        id: 1,
        firstName: "Nick",
        lastName: "Stepanov",
        email: "fesfs@ffff.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 2,
        firstName: "Student",
        lastName: "2",
        email: "student2@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 3,
        firstName: "Student",
        lastName: "3",
        email: "student3@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 4,
        firstName: "Student",
        lastName: "4",
        email: "student4@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 5,
        firstName: "Student",
        lastName: "5",
        email: "student5@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 6,
        firstName: "Student",
        lastName: "6",
        email: "student6@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
    {
        id: 7,
        firstName: "Student",
        lastName: "7",
        email: "student7@gmail.com",
        address: "",
        created: new Date().getTime(),
    },
]